# Generated by Django 4.2.7 on 2026-05-27 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', '🟢 Easy'), ('MEDIUM', '🟡 Medium'), ('HARD', '🔴 Hard'), ('ELITE', '💀 Elite')], max_length=10)),
                ('time_limit_ms', models.IntegerField(default=1000)),
                ('memory_limit_mb', models.IntegerField(default=256)),
                ('examples', models.JSONField(default=list)),
                ('test_cases', models.JSONField(default=list)),
                ('starter_code', models.JSONField(default=dict)),
                ('editorial', models.TextField(blank=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_accepted', models.IntegerField(default=0)),
                ('battle_weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#00ffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_set', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problems.tag'),
        ),
    ]
