# Generated by Django 4.2.7 on 2026-05-27 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('BATTLE', 'Battle'), ('SOLVE', 'Problem Solving'), ('STREAK', 'Streak'), ('SPECIAL', 'Special')], max_length=20)),
                ('xp_reward', models.IntegerField(default=50)),
                ('condition_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('rank', models.CharField(choices=[('UNRANKED', '⚫ Unranked'), ('BRONZE', '🥉 Bronze'), ('SILVER', '🥈 Silver'), ('GOLD', '🥇 Gold'), ('PLATINUM', '💠 Platinum'), ('DIAMOND', '💎 Diamond'), ('MASTER', '🔮 Master'), ('GRANDMASTER', '👑 Grandmaster')], default='UNRANKED', max_length=20)),
                ('battles_played', models.IntegerField(default=0)),
                ('battles_won', models.IntegerField(default=0)),
                ('battles_lost', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('max_win_streak', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('correct_submissions', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
