# Generated by Django 4.2.7 on 2026-05-27 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CASUAL', 'Casual'), ('RANKED', 'Ranked'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='CASUAL', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for opponent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DRAW', 'Draw')], default='WAITING', max_length=20)),
                ('p1_health', models.IntegerField(default=100)),
                ('p2_health', models.IntegerField(default=100)),
                ('p1_rating_before', models.IntegerField(default=0)),
                ('p2_rating_before', models.IntegerField(default=0)),
                ('p1_rating_delta', models.IntegerField(default=0)),
                ('p2_rating_delta', models.IntegerField(default=0)),
                ('time_limit', models.IntegerField(default=1800)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_p2', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.problem')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('PE', 'Pending')], default='PE', max_length=5)),
                ('test_cases_passed', models.IntegerField(default=0)),
                ('test_cases_total', models.IntegerField(default=0)),
                ('runtime_ms', models.IntegerField(default=0)),
                ('memory_mb', models.FloatField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='battles.battle')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CASUAL', 'Casual'), ('RANKED', 'Ranked'), ('CUSTOM', 'Custom'), ('TOURNAMENT', 'Tournament')], default='RANKED', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
